BlogSpot/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("blogapp.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from blogapp import views

urlpatterns=[
path('accounts/signup',views.SignUpView.as_view(),name="signup"),
    path('accounts/login',views.LoginView.as_view(),name="signin"),
    path('home',views.IndexView.as_view(),name="home"),
    path('users/profile/add',views.UserProfileView.as_view(),name='add-profile'),
    path('users/profile/details',views.UserDetailView.as_view(),name='details'),
    path('users/password/change',views.PasswordResetView.as_view(),name='pwd-reset'),
    path('users/profile/change/<int:user_id>',views.ProfileUpdateView.as_view(),name="profile-update"),
    path('users/pic/change<int:user_id>',views.ProfilePicUpdateView.as_view(),name="pic-change"),
    path('post/comment/<int:post_id>',views.add_comment,name='add-comment'),
    path('post/erase/<int:blog_id>',views.remove_post,name='remove-post'),
    path('user/follow/<int:user_id>',views.follow_friend,name='follow-friend'),
    path('post/like/add/<int:post_id>',views.add_like,name='add-like'),



    path('accounts/logout',views.sign_out,name="sign-out")
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
import random


class UserProfile(models.Model):
    profile_pic=models.ImageField(upload_to="profilepics",null=True)
    bio=models.CharField(max_length=120)
    phone=models.CharField(max_length=15)
    dob=models.DateField(null=True)
    options=(
        ("Male","Male"),
        ("Female","Female"),
        ("Other","Other")
    )
    gender=models.CharField(max_length=12,choices=options,default="Male")
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="users")
    following=models.ManyToManyField(User,related_name="followings",blank=True)

    @property
    def fetch_following(self):
        my_followings=[user for user in self.following.all()]
        return my_followings

        # return self.following.all()
    #
    # def fetch_following_count(self):
    #     return self.fetch_following.count()

    @property
    def fetch_following_count(self):
        return len(self.fetch_following)

        # return self.following.all()
    @property
    def get_invitations(self):
        all_users=UserProfile.objects.all().exclude(user=self.user) # fetch all users except current user
        user_list=[userprofile.user for userprofile in all_users]
        myfollowers=[u for u in self.fetch_following]
        invitations=[user for user in user_list if user not in myfollowers]   # exclude my folloings from all users
        return invitations

    def get_followers(self):
        all_user_profile=UserProfile.objects.all()
        my_followers=[]
        for profile in all_user_profile:
            if self.user in profile.fetch_following:
                my_followers.append(profile)
        return my_followers
    def my_follower_count(self):
        return len(self.get_followers)



class Blogs(models.Model):

    description=models.CharField(max_length=260)
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name="author")
    image=models.ImageField(upload_to="blogimages",null=True)
    liked_by=models.ManyToManyField(User)
    posted_date=models.DateTimeField(auto_now_add=True)



    @property
    def get_like_count(self):
        like_count=self.liked_by.all().count()
        return like_count
    @property
    def get_liked_users(self):
        liked_users=self.liked_by.all()
        users=[user.username for user in liked_users]
        return users





    def __str__(self):
        return self.title

class Comments(models.Model):
    blog=models.ForeignKey(Blogs,on_delete=models.CASCADE)
    comment = models.CharField (max_length=250)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.comment






# Create your models here.

# users [ 1. ashiq   2. rinsha   3. zammu ]

blogapp/forms.py
from django.contrib.auth.models import User
from django.forms import  ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from blogapp.models import UserProfile,Blogs,Comments


class UserRegForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"
        ]
        widgets = {
            "email": forms.EmailInput (attrs={'class': 'form-control' }),
            "username": forms.TextInput (attrs={'class': 'form-control'}),
            "last_name": forms.TextInput (attrs={'class': 'form-control'}),
            "first_name": forms.TextInput (attrs={'class': 'form-control'}),
        }

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control rounded-pill'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control rounded-pill'}))

class UserProfileForm(ModelForm):
    class Meta:
        model=UserProfile
        exclude=("user","following")
        widgets={
            "dob":forms.DateInput(attrs={'class':'form-control','type':'date'}),
            "profile_pic":forms.FileInput(attrs={'class':'form-control rounded-pill'}),
            "bio": forms.TextInput (attrs={'class': 'form-control rounded-pill'}),
            "phone": forms.TextInput (attrs={'class': 'form-control rounded-pill'}),
            "gender": forms.TextInput (attrs={'class': 'form-control rounded-pill'}),

        }

class PasswordResetForm(forms.Form):
    old_pwd=forms.CharField(widget=forms.PasswordInput)
    new_pwd=forms.CharField(widget=forms.PasswordInput)
    confirm_pwd=forms.CharField()

class BlogForm(ModelForm):
    class Meta:
        model=Blogs
        fields=[

            "description",
            "image"
        ]
        widgets={

            "description":forms.Textarea(attrs={'class':'form-control'}),
            "image":forms.FileInput(attrs={'class':'form-control'})
        }

class ProfilePicUpdateForm(ModelForm):
    class Meta:
        model=UserProfile
        fields=[
            "profile_pic"
        ]
        widgets={
            "profile_pic":forms.FileInput(attrs={'class':'form-control'})
        }

class CommentsForm(ModelForm):
    class Meta:
        model=Comments
        fields=[
            "comment"
        ]
        widgets={
            "comment":forms.TextInput(attrs={'class':'form-control'})
        }

blogapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,CreateView,FormView,TemplateView,DetailView,UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from blogapp.forms import UserRegForm,LoginForm,UserProfileForm,PasswordResetForm,BlogForm,ProfilePicUpdateForm,CommentsForm
from django.contrib.auth import authenticate,login,logout
from blogapp.models import UserProfile,Blogs,Comments
from django.contrib import messages
from django.utils.decorators import method_decorator

# Create your views here.

def signin_required(fn):
    def wrapper(request,*args,**kwargs):
        if request.user.is_authenticated:
            return fn(request,*args,**kwargs)
        else:
            messages.error(request,"User must be logged in")
            return redirect("signin")
    return wrapper




class SignUpView(CreateView):
    form_class=UserRegForm
    template_name="reg.html"
    model=User
    success_url=reverse_lazy("signin")

class LoginView(FormView):
    model=User
    template_name="login.html"
    form_class=LoginForm

    def post(self,request,*args,**kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            user=authenticate(request,username=username,password=password)
            if user:
                print("success")
                login(request,user)
                return redirect("home")
            else:
                return render(request,self.template_name,{'form':form})

@method_decorator(signin_required,name='dispatch')
class IndexView(CreateView):
    model = Blogs
    form_class = BlogForm
    success_url = reverse_lazy("home")
    template_name="home.html"
    def form_valid(self, form):
        form.instance.author=self.request.user
        self.object = form.save ()
        messages.success(self.request,"Post has been saved")
        return super ().form_valid (form)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        blogs=Blogs.objects.all().order_by("-posted_date")
        context["blogs"]=blogs
        comment_form=CommentsForm()
        context["comment_form"]=comment_form
        return context



@method_decorator(signin_required,name='dispatch')
class UserProfileView(CreateView):
    model = UserProfile
    template_name = "addprofile.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success (self.request, "profile has been created")
        self.object = form.save ()
        return super ().form_valid (form)

@method_decorator(signin_required,name='dispatch')
class UserDetailView(TemplateView):

    template_name = "userdetail.html"

@method_decorator(signin_required,name='dispatch')

class PasswordResetView(FormView):
    template_name = "pwd-reset.html"
    form_class = PasswordResetForm

    def post(self,request,*args,**kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            oldpwd=form.cleaned_data.get("old_pwd")
            newpwd=form.cleaned_data.get("new_pwd")
            confirmpwd = form.cleaned_data.get ("confirm_pwd")
            user=authenticate(request,username=request.user.username,password=oldpwd)
            if user:
                user.set_password(confirmpwd)
                user.save()
                messages.success(request,"Password changed successfully")
                return redirect("signin")
            else:
                messages.error(request,"invalid credentials")
                return render(request,self.template_name,{'form':form})

@method_decorator(signin_required,name='dispatch')
class ProfileUpdateView(UpdateView):
    form_class = UserProfileForm
    template_name = "update-user.html"
    model = UserProfile
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"
    def form_valid(self, form):
        messages.success(self.request,"Profile hasbeen Updated")
        self.object = form.save ()
        return super ().form_valid (form)

class ProfilePicUpdateView(UpdateView):
    form_class = ProfilePicUpdateForm
    template_name = "propic-update.html"
    model = UserProfile
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"
    def form_valid(self, form):
        messages.success(self.request,"Profile Pic hasbeen Updated")
        self.object = form.save ()
        return super ().form_valid (form)

def add_comment(request,*args,**kwargs):
    if request.method=='POST':

        blog_id=kwargs.get('post_id')
        blog=Blogs.objects.get(id=blog_id)
        user=request.user
        comment=request.POST.get('comment')
        Comments.objects.create(blog=blog,comment=comment,user=user)
        messages.success(request,"comment has been posted")
        return redirect('home')

def add_like(request,*args,**kwargs):
    blog_id=kwargs.get('post_id')
    blog = Blogs.objects.get (id=blog_id)
    user=request.user
    blog.liked_by.add(request.user)
    blog.save()
    return redirect('home')

def remove_post(request,*args,**kwargs):
    blog_id=kwargs.get("post_id")
    blog=Blogs.objects.get(id=blog_id)
    blog.delete()
    messages.success(request,"post has been removed")
    return redirect("home")

def follow_friend(request,*args,**kwargs):
    follower_id=kwargs.get('user_id')
    user_profile=UserProfile.objects.get(user=request.user)
    follower=User.objects.get(id=follower_id)
    user_profile.following.add(follower)
    messages.success(request,"you have followed")
    return redirect("home")








def sign_out(request,*args,**kwargs):
    logout(request)
    return redirect("signin")

blogapp/templates/addprofile.html
{%extends 'index.html'%}

{%block body_block%}

<div class="container" style="padding-top:26px;">

            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary" id="addbtn">
            </form>

</div>

{%endblock%}

blogapp/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/48cc297c0b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script src="https://kit.fontawesome.com/48cc297c0b.js" crossorigin="anonymous"></script>
</head>
<body>

<nav>
    <div class="nav-left">
        <div class="blog"><h1>BlogSpot</h1></div>
        <ul>
            <li><img src="{%static 'images/notification.png'%}"></li>
            <li><img src="{%static 'images/inbox.png'%}"></li>

            <li><img src="{%static 'images/video.png'%}"></li>

        </ul>
    </div>
    <div class="nav-right">

        <div class="search-box">
            <img src="{%static 'images/search.png'%}" alt="">
            <input type="text" placeholder="search">
        </div>
        <div class="nav-user-icon online">
            {%if request.user.users.profile_pic%}
            <a href="{%url 'pic-change' request.user.users.id%}">
                <img src="{{request.user.users.profile_pic.url}}" alt=""></a>
            {%endif%}
        </div>
    </div>
    <!--    settings-menu-->


</nav>


<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        {%if messages%}
        {%for msg in messages%}
        {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>"{{msg}}"</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}

        {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>"{{msg}}"</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}
        {%endfor%}
        {%endif%}
    </div>
    <div class="col-4">

    </div>


    <div class="abc">
        <!--    left-sidebar-->
        <div class="left-sidebar">
            <div class="imp-links">

                <a href="{%url 'home'%}"><img src="{%static 'images/profile-home.png'%}"> Home</a>

                <a href="{%url 'details'%}"><img src="{%static 'images/friends.png'%}"> Profile</a>

                <a href="{%url 'add-profile'%}"><img src="{%static 'images/group.png'%}"> Group</a>
                <a href="#"><img src="{%static 'images/marketplace.png'%}"> Market Place</a>
                <a href="{%url 'sign-out'%}"><img src="{%static 'images/logout.png'%}">Log Out</a>
                <a href="">See More</a>

            </div>
            <div class="shortcut-links">
                <p>Your Shortcuts</p>
                <a href="">
                    <img src="{%static 'images/shortcut-1.png'%}" alt=""> Web Developers
                </a>
                <a href="">
                    <img src="{%static 'images/shortcut-2.png'%}" alt=""> Web Design Course
                </a>
                <a href="">
                    <img src="{%static 'images/shortcut-3.png'%}" alt=""> Full Stack Development
                </a>
                <a href="">
                    <img src="{%static 'images/shortcut-4.png'%}" alt=""> Experts
                </a>
            </div>
        </div>
        <!--    main-content-->
        <div class="main-content">

            <div class="story_gallery">
                <div class="story story1">
                    <img src="{%static 'images/upload.png'%}" alt="">
                    <p>Post Story</p>
                </div>
                <div class="story story2">
                    <img src="{%static 'images/member-2.png'%}" alt="">
                    <p>Rinsha Karim</p>
                </div>
                <div class="story story3">
                    <img src="{%static 'images/member-3.png'%}" alt="">
                    <p>Hazrat Zamaan</p>
                </div>
                <div class="story story4">
                    <img src="{%static 'images/member-4.png'%}" alt="">
                    <p>Ashiq Hassan</p>
                </div>
                <div class="story story5">
                    <img src="{%static 'images/member-5.png'%}" alt="">
                    <p>Vivek Joy</p>
                </div>

            </div>


            <div class="write_post_container">
                <div class="user_profile">
                    <img src="{{request.user.users.profile_pic.url}}">
                    <div>
                        <p>{{request.user}}</p>
                        <small>Public<i class="fa-solid fa-caret-down"></i></small>
                    </div>
                </div>

                <div class="post-input-container">

                    <form action="" method="post" enctype="multipart/form-data" class="mt-5">
                        {%csrf_token%}


                        <textarea rows="3" name="description"
                                  placeholder="What's on your mind {{request.user}}.?"></textarea>
                        <div class="add-post-links">
                            <a href="#"> <img src="{%static 'images/live-video.png'%}" alt="">Live Video</a>
                            <a href="#"> <img src="{%static 'images/photo.png'%}" alt=""><input type="file" name="image"
                                                                                                >Photo Video</a>

                            <a href="#"> <img src="{%static 'images/feeling.png'%}" alt="">Feeling/Activity</a>
                            <input type="submit" value="POST">
                        </div>

                    </form>


                </div>


                <body>

                {%block body_block%}

                {%endblock%}

                </body>


                <!--    right-sidebar-->
                <div class="right-sidebar">
                    <div class="sidebar-title">
                        <h4>Events</h4>
                        <a href="#">See All</a>
                    </div>

                    <div class="event">
                        <div class="left-event">
                            <h3>18</h3>
                            <span>March</span>
                        </div>
                        <div class="right-event">
                            <h4>Social Media</h4>
                            <p><i class="fa-solid fa-location-dot"></i> Info Park</p>
                            <a href="#">More Info</a>
                        </div>
                    </div>

                    <div class="event">
                        <div class="left-event">
                            <h3>22</h3>
                            <span>June</span>
                        </div>
                        <div class="right-event">
                            <h4>Mobile Marketing</h4>
                            <p><i class="fa-solid fa-location-dot"></i> Info Park</p>
                            <a href="#">More Info</a>
                        </div>
                    </div>

                    <div class="sidebar-title">
                        <h4>Advertisements</h4>
                        <a href="#">Close</a>
                    </div>
                    <img src="{%static 'images/advertisement.png'%}" class="sidebar-ads">

                    <div class="sidebar-title">
                        <h4>Conversations</h4>
                        <a href="#">Hide Chat</a>
                    </div>

                    <div class="online-list">
                        <div class="online">
                            <img src="{%static 'images/member-1.png'%}" alt="">
                        </div>
                        <p>Rinsha Karim</p>
                    </div>

                    <div class="online-list">
                        <div class="online">
                            <img src="{%static 'images/member-2.png'%}" alt="">
                        </div>
                        <p>Hazrat Zamaan</p>
                    </div>

                    <div class="online-list">
                        <div class="online">
                            <img src="{%static 'images/member-3.png'%}" alt="">
                        </div>
                        <p>Ashiq Hassan</p>
                    </div>

                </div>
            </div>

            <div class="footer">
                <p>Copyright 2022 - Ashiq Hassan</p>
            </div>


</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</html>

blogapp/templates/home.html
{%extends 'index.html'%}
{%load static%}
{%block body_block%}


 <div class="post-input-container">

                <form action="" method="post" enctype="multipart/form-data" class="mt-5">
                    {%csrf_token%}


                    <textarea rows="3" name="description"
                              placeholder="What's on your mind {{request.user}}.?"></textarea>
                    <div class="add-post-links">
                        <a href="#"> <img src="{%static 'images/live-video.png'%}" alt="">Live Video</a>
                        <a href="#"> <img src="{%static 'images/photo.png'%}" alt=""><input type="file" name="image"
                        >Photo Video</a>

                        <a href="#"> <img src="{%static 'images/feeling.png'%}" alt="">Feeling/Activity</a>
                        <input type="submit" value="POST">
                    </div>

                </form>


            </div>



<div class="post-container">
    <div class="post-row">
        <div class="user_profile">
            <img src="{{request.user.users.profile_pic.url}}">
            <div>
                <p>{{request.user}}</p>
            </div>
        </div>

        <a href=""><i class="fas fa-ellipsis-v"></i></a>
    </div>


    {%for blog in blogs%}


    <p class="post-text">{{blog.title}}</p>
    <p class="post-text">{{blog.description}}</p>
    <img src="{{blog.image.url}}" class="post-img">
    <p class="post-text">Posted by: {{blog.author}}</p>
    <span>Posted on: {{blog.posted_date}}</span>

    <div class="post-row">

        <div class="activity-icons">
            <div><a href="{%url 'add-like' blog.id%}"><img src="{%static 'images/like-blue.png'%}"></a>
                <p class="like">{{blog.get_like_count}} </p>
            </div>
            <div>

                <p>
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseWidthExample" aria-expanded="false"
                            aria-controls="collapseWidthExample">
                        Comment
                    </button>
                </p>
                <div style="min-height: 120px;">
                    <div class="collapse collapse-horizontal" id="collapseWidthExample">
                        <div class="card card-body" style="width: 300px;">
                            <form action="{%url 'add-comment' blog.id%}" method="post">
                                {%csrf_token%}
                                {{comment_form.as_p}}
                                <input type="submit" class="btn btn-primary">
                            </form>
                        </div>
                    </div>
                </div>

                <p>
                    <a class="btn" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false"
                       aria-controls="multiCollapseExample1">
                        <img src="{%static 'images/comments.png'%}">
                    </a>

                </p>
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div class="card card-body">

                        {%for comment in blog.comments_set.all%}

                        <div class="breadcrumbs mt-4">
                            <p><strong>{{comment.user}}:</strong></p>
                            <p> {{comment.comment}}</p>

                            <p>{{blog.user.profile_pic}}</p>
                        </div>

                        {%endfor%}

                    </div>
                </div>


            </div>
            <div><img src="{%static 'images/share.png'%}"></div>
        </div>
        <div class="post-profile-icon">
            <img src="{{request.user.users.profile_pic.url}}"><i class="fa-solid fa-caret-down"></i>
        </div>
    </div>


    {%endfor%}

</div>
</div>

<button type="button" class="load-more">Load More</button>

</div>


{%endblock%}

blogapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>




<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        {%if messages%}
        {%for msg in messages%}
        {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>"{{msg}}"</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}

        {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>"{{msg}}"</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}
        {%endfor%}
        {%endif%}
    </div>
    <div class="col-4">

    </div>
</div>
</div>


<section style="background-color: #9A616D;">

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">



        </div>
        <div class="col-4"></div>
    </div>

    <section class="vh-100 gradient-custom" >
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>

                 <form action="" method="post">
                {%csrf_token%}
                     {{form.errors}}
              <div class="form-outline form-white mb-4">
                <input type="text" id="id_username" class="form-control form-control-lg" name="username"/>
                <label class="form-label" for="id_username">Username</label>
              </div>

              <div class="form-outline form-white mb-4">
                <input type="password" id="id_password" class="form-control form-control-lg" name="password"/>
                <label class="form-label" for="id_password">Password</label>
              </div>


              <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>

              <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

                      </form>
              <div class="d-flex justify-content-center text-center mt-4 pt-1">
                <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
              </div>

            </div>

            <div>
              <p class="mb-0">Don't have an account? <a href="{%url 'signup'%}" class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

</section>
</div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

</html>

blogapp/templates/propic-update.html
{%extends 'index.html'%}

{%block body_block%}

<<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}

               {{form.as_p}}

                <input type="submit" value="Update">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>

{%endblock%}

blogapp/templates/pwd-reset.html
{%extends 'index.html'%}

{%block body_block%}

<<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>

{%endblock%}

blogapp/templates/update-user.html
{%extends 'index.html'%}

{%block body_block%}

<<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>

{%endblock%}